[robot_dashboard] Fix error 'NoneType' object has no attribute '_paused'
**Issue**
Callback _message_cb is called before ConsoleWidget is instantiated, so during the initializing of the robot_dashboard plugin the following error can keep happening for awhile.

```
[ERROR] [WallTime: 1490999099.241694] [4.180000] bad callback: <bound method ConsoleDashWidget._message_cb of <rqt_robot_dashboard.console_dash_widget.ConsoleDashWidget object at
0x7f58f3b0c9d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_robot_dashboard/console_dash_widget.py", line 120, in _message_cb
    if not self._console._paused:
AttributeError: 'NoneType' object has no attribute '_paused'
```

**Fix**

Move ConsoleWidget instantiation before the plugin starts subscribing.